project_id = "reinado-2026"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 17

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:3001"
additional_redirect_urls = ["http://localhost:3000/**", "http://localhost:3001/**"]
enable_signup = true
enable_anonymous_sign_ins = true

[auth.email]
enable_signup = false
double_confirm_changes = true
enable_confirmations = true

[functions.emitir-voto]
verify_jwt = true

[functions.generar-codigos]
verify_jwt = true

[functions.crear-admin-inicial]
verify_jwt = false

[functions.auditoria-sistema]
verify_jwt = true

[functions.resultados-publicos]
verify_jwt = false
